In [4]:
# Q1
import numpy as np
arr=np.arange(1,24,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
# Q2
arr=np.linspace(5,45,9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [9]:
# Q3
arr1= np.arange(1, 10)
arr2=np.linspace(1, 9, 9)
print(arr1,arr2)
print(arr1.dtype,arr2.dtype)

[1 2 3 4 5 6 7 8 9] [1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64 float64


In [12]:
# Q4
arr=np.eye(6,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [13]:
# Q5
arr=np.full((3,4),5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
12
2


In [15]:
# Q6
a = np.array([2, 4, 6]) 
b = np.array([2.0, 4.0, 6.0])
print(a.dtype,b.dtype)
b=b.astype(int)
print(b.dtype)

int64 float64
int64


In [16]:
# Q7
a=np.array([10.9, 25.5, 39.99]).astype(int)
print(a)

[10 25 39]


In [17]:
# Q8
arr = np.arange(10, 101, 10) 
print(arr[3])
print(arr[-1])
print(arr[-2])

40
100
90


In [19]:
# Q9
arr = np.arange(10, 101, 10) 
print(arr[2:6])
print(arr[::-1])

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


In [21]:
# Q10
arr = np.arange(1, 21)
print(arr[1::3])
 

[ 2  5  8 11 14 17 20]


In [24]:
# Q11
arr=np.arange(1,21)
print(arr[2:-2])


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
