In [4]:
# Q1
import numpy as np
arr=np.arange(1,24,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
# Q2
arr=np.linspace(5,45,9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [9]:
# Q3
arr1= np.arange(1, 10)
arr2=np.linspace(1, 9, 9)
print(arr1,arr2)
print(arr1.dtype,arr2.dtype)

[1 2 3 4 5 6 7 8 9] [1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64 float64


In [12]:
# Q4
arr=np.eye(6,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
